############################
## CHANGE THESE
############################

baseURL: "https://PureRandomGit.github.io/Portfolio"
title: Portfolio

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
